language: python

python:
  - 2.7
  - 3.5
  - 3.6


install:
  - pip install coverage
  - pip install coveralls

script:

  - coverage run -a --source=dicetables setup.py test
  - coverage report -m
  # Run the doctests
  - python doctests.py

after_success:
  - coveralls
